# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='unidades_de_medida',
            new_name='unidad_de_medida',
        ),
    ]
