# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_auto_20180818_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_compra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
